/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import java.util.List;

/**
 *
 * @author Admin
 */
public class Sirvice extends javax.swing.JPanel {

    /**
     * Creates new form Sirvice
     */

    private final List<String> selectedServices;

    public Sirvice() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cccd = new javax.swing.JTextField();
        checkRC = new javax.swing.JCheckBox();
        checkB = new javax.swing.JCheckBox();
        checkAS = new javax.swing.JCheckBox();
        txtdate = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        cccd.setBackground(new java.awt.Color(239, 239, 239));
        cccd.setToolTipText("Please enter");
        cccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cccdActionPerformed(evt);
            }
        });

        checkRC.setBackground(new java.awt.Color(249, 249, 249));
        checkRC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkRC.setText("Room Cleaning");
        checkRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRCActionPerformed(evt);
            }
        });

        checkB.setBackground(new java.awt.Color(249, 249, 249));
        checkB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkB.setText("Breakfast");
        checkB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBActionPerformed(evt);
            }
        });

        checkAS.setBackground(new java.awt.Color(249, 249, 249));
        checkAS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkAS.setText("Airport Shuttle");
        checkAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkASActionPerformed(evt);
            }
        });

        txtdate.setBackground(new java.awt.Color(237, 237, 237));

        btn.setBackground(new java.awt.Color(204, 255, 204));
        btn.setText("Enter");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CUSTOMER SERVICE");

        jLabel2.setText("identyti card");

        jLabel3.setText("End date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(354, 354, 354))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAS, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkRC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(checkRC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(checkAS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        List<Integer> selectedServiceCodes = new ArrayList<>();

        if (checkB.isSelected()) {
            selectedServiceCodes.add(2); // Assuming service_code for Breakfast is 2
        }
        if (checkAS.isSelected()) {
            selectedServiceCodes.add(3); // Assuming service_code for Airport Shuttle is 3
        }
        if (checkRC.isSelected()) {
            selectedServiceCodes.add(1); // Assuming service_code for Room Cleaning is 1
        }
        String useDate = txtdate.getText();
        String cccd = this.cccd.getText();

        try (var connection = ds.getConnection()) {
            // Bắt đầu một giao dịch
            connection.setAutoCommit(false);

            // Lưu thông tin sử dụng dịch vụ vào bảng use_service
            String insertUseServiceSql = "INSERT INTO use_service (customer_code, service_code, use_date) VALUES (?, ?, ?)";
            try (PreparedStatement insertUseServiceStatement = connection.prepareStatement(insertUseServiceSql)) {
                for (Integer serviceCode : selectedServiceCodes) {
                    insertUseServiceStatement.setString(1, cccd);
                    insertUseServiceStatement.setInt(2, serviceCode);
                    insertUseServiceStatement.setString(3, useDate); // Set use_date

                    insertUseServiceStatement.executeUpdate();
                }
            }

            // Kết thúc giao dịch và lưu các thay đổi
            connection.commit();

            JOptionPane.showMessageDialog(this, "Service usage information saved successfully!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error when saving information: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnActionPerformed

    private void checkRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRCActionPerformed

    private void cccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cccdActionPerformed

    private void checkASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkASActionPerformed

    private void checkBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JTextField cccd;
    private javax.swing.JCheckBox checkAS;
    private javax.swing.JCheckBox checkB;
    private javax.swing.JCheckBox checkRC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
